name: Release

on:
  push:
    tags:
      # Publish on any tag that looks like a semantic version e.g. 1.2.3
      - '*.*.*'

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
      - run: uv build
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project -p 3.11 --with dist/*.whl tests/test_smoke.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project -p 3.11 --with dist/*.tar.gz tests/test_smoke.py
      - run: uv publish --trusted-publishing always
